### ISSUE TITLE
Interaction between RcppArmadillo and RcppSpdlog seen: `assert` and `stderr` messages from R CMD check 

### ISSUE THREAD

**Issue by jdstamp** [eddelbuettel/rcppspdlog#9] opened 2021-04-27 13:19 UTC
## Error description

I implemented standard Github actions for checking my package on push. 

I am running the `devtools::check()` on 

- Ubuntu-20.04 
- macOS-latest 

In Ubuntu, no warnings are produced. 

In macOS the check fails during test execution with this warning:

```
>❯ checking compiled code ... WARNING
  File ‘mvMAPIT/libs/mvMAPIT.so’:
    Found ‘___assert_rtn’, possibly from ‘assert’ (C)
      Object: ‘MAPIT.o’
    Found ‘___stderrp’, possibly from ‘stderr’ (C)
      Object: ‘MAPIT.o’
  
 > Compiled code should not call entry points which might terminate R nor
  write to stdout/stderr instead of to the console, nor use Fortran I/O
  nor system RNGs.
  
  > See ‘Writing portable packages’ in the ‘Writing R Extensions’ manual.
```
  
The error occurs during execution of tests where I just run the function below.

## Code

  I was trying to follow exactly the example for usage in a package from the blog entry: https://dirk.eddelbuettel.com/code/rcpp.spdlog.html. Here is what the logger part looks like:
  
  DESCRIPTION:
  
  ```
  LinkingTo: Rcpp, RcppArmadillo, testthat, RcppSpdlog
  ```
  Code
  
  ``` 
#define SPDLOG_DISABLE_DEFAULT_LOGGER 1
#include <RcppSpdlog>
#include <spdlog/stopwatch.h>           // also support stopwatch feature

...

Rcpp::List MAPITCpp(arma::mat X,
                 arma::mat Y,
                 ...)
{

     std::string logname = "mvMAPIT";
    auto logger = spdlog::get(logname);                         // retrieve existing one
    if (logger == nullptr) logger = spdlog::r_sink_mt(logname);     // or create new one if needed
    spdlog::set_default_logger(logger);                         // and set as default

    spdlog::stopwatch sw;                                   // instantiate a stop watch

    int i;
    const int n = X.n_cols;
    const int p = X.n_rows;
    const int d = Y.n_rows;
    int q = 0;

    logger->info("Number of samples: {}", n);
    logger->info("Number of SNPs: {}", p);
    logger->info("Number of phenotypes: {}", d);
    logger->info("Test method: {}", testMethod);
    logger->info("Phenotype covariance model: {}", phenotypeCovariance);
    
   ...
   
   }
```

Github PR in my repository: https://github.com/lcrawlab/mvMAPIT/pull/10/files

## Expected behaviour

I would like to be able to use logging both under Ubuntu and macOS without breaking the `R CMD check`.

**Comment by eddelbuettel** [comment] 2021-04-27 13:27
Hm, we will need to take a closer look and decompose this.  If and when we set this up (over a few commits here and upstream where @gabime was very helpful and receptive) we tried to make sure that with this setup, only permitted R facilities would be used.  And if you look at the [CRAN Package Check Results page](https://cloud.r-project.org/web/checks/check_results_RcppSpdlog.html) you see we are clean on macOS too, and I believe our example uses the suggested method. 

I.e. what happens if you use the method you used to trigger a warning on the RcppSpdlog source package itself?

**Comment by eddelbuettel** [comment] 2021-04-27 13:33
Your issuer above is from your source file MAPIT as in 

```
File ‘mvMAPIT/libs/mvMAPIT.so’:
    Found ‘___assert_rtn’, possibly from ‘assert’ (C)
      Object: ‘MAPIT.o’
    Found ‘___stderrp’, possibly from ‘stderr’ (C)
      Object: ‘MAPIT.o’
```

so you need to see what you can do differently.  Right now your header has

```
#include <string>
#include <iostream>

#define SPDLOG_DISABLE_DEFAULT_LOGGER 1
#include <RcppSpdlog>
#include <spdlog/stopwatch.h>           // also support stopwatch feature
#include <Rcpp.h>
using namespace Rcpp;
```

which is a bit different from what I have in the (working !!) example [sc/exampleRsink.cpp](https://github.com/eddelbuettel/rcppspdlog/blob/master/src/exampleRsink.cpp):

```

// this portmanteau include also defines the r_sink we use below, and which
// diverts all logging to R via the Rcpp::Rcout replacement for std::cout
#include <RcppSpdlog>
#include <spdlog/stopwatch.h>   		// also support stopwatch feature
```

For starters, no need to re-include `Rcpp.h`.  No need to include common headers.  Can you try to simplify?

**Comment by jdstamp** [comment] 2021-04-27 14:36
Hi @eddelbuettel , thank you for getting back to me so quickly!

I am new to `R` and `C++` and I am taking over the development of a package that already has a lot of code that was not properly set up and developed as an R package prior to my attempt to restructure it accordingly. This is to say that I did not question many existing things based on the fact that it seemed to be working.

**1. Simplify**
I am trying to simplify the header. From what I understand, I still need to include 

```
#include <vector>
#include <string>
```

because there are variables declared as these types (https://stackoverflow.com/questions/27350164/when-do-i-use-include-string-at-the-start-of-a-c-program).

I removed the duplication of `#include <Rcpp.h>`. I also removed `#include <iostream>`. This include looked suspicious because it provides the standard input/output streams.

Neither change removed the warning.

**2. Further decomposition**
What do you mean exactly by
> I.e. what happens if you use the method you used to trigger a warning on the RcppSpdlog source package itself?

**Comment by eddelbuettel** [comment] 2021-04-27 16:25
Howdy.

No shame in being brand new to R, C++ and Rcpp.  At some point we all were.

Re 1) "headers":   Experience has taught many of us that order can matter, and sometimes it is easiest to just follow along. Here you can remove `<vector>` and `<string>` as ... `<Rcpp.h>` will bring them in.  That may, or may not, help with the issue.

Re 2) "method":  You manage to elicit the bad warning from using a command on your package.  Can you the same command (on the platform) on the source package RcppSpdlog and see what happens?  I would love to know if the package itself triggered this.  If it doesn't it means we may need to (temporarily) take the scalpel to your package and remove code til the warning goes away to find the segment causing the warning.

**Comment by jdstamp** [comment] 2021-04-27 16:52
I am trying to follow the method.

## What I did

1. `git clone https://github.com/eddelbuettel/rcppspdlog.git`
2. copy `MAPIT.h` file into `rcppspdlog/src`
3. Comment out the `#include`s in `exampleRsink.cpp` and insert `#include "MAPIT.h"`
4. run `usethis::use_rcpp_armadillo()` in R console to make it available
5. run `devtools::check()` in R console

## Resulting warning

>   File ‘RcppSpdlog/libs/RcppSpdlog.so’:
    Found ‘___assert_rtn’, possibly from ‘assert’ (C)
      Object: ‘exampleRsink.o’
    Found ‘___stderrp’, possibly from ‘stderr’ (C)
      Object: ‘exampleRsink.o’

## Files

**MAPIT.h** (updated)
```
#pragma once

#define ARMA_64BIT_WORD 1
#include <RcppArmadillo.h>

#include <Rcpp.h>

#ifdef _OPENMP
#include <omp.h>
#endif

#define SPDLOG_DISABLE_DEFAULT_LOGGER 1
#include <RcppSpdlog>
#include <spdlog/stopwatch.h>           // also support stopwatch feature

arma::mat GetLinearKernel(arma::mat X);
arma::mat ComputePCs(arma::mat X, int top);
//TODO: tests
arma::mat ComputeProjectionMatrix(int n, arma::mat b);
double ProductTrace(arma::mat a, arma::mat b);
```

**exampleRsink.cpp**:
```
#include "MAPIT.h"
// this portmanteau include also defines the r_sink we use below, and which
// diverts all logging to R via the Rcpp::Rcout replacement for std::cout
//#include <RcppSpdlog>
//#include <spdlog/stopwatch.h>   		// also support stopwatch feature

//' spdlog Example using a sink for R
//'
//' A simple example invoking a derived R/Rcpp logger. Also demonstrates the
//' stopwatch feature. For more features see the 'spdlog' documnetation.
//'
//' Note that this no longer triggers R warnings thanks to excellent help by
//' Gabi Melman.
//' @return None
//' @examples
//' exampleRsink()
// [[Rcpp::export]]
void exampleRsink() {

    std::string logname = "fromR"; 							// fix a name for this logger
    auto sp = spdlog::get(logname);       					// retrieve existing one
    if (sp == nullptr) sp = spdlog::r_sink_mt(logname);   	// or create new one if needed
    spdlog::set_default_logger(sp);                         // and set as default

    spdlog::stopwatch sw;       							// instantiate a stop watch

    // change log pattern (changed from [%H:%M:%S %z] [%n] [%^---%L---%$] )
    spdlog::set_pattern("[%H:%M:%S.%f] [%n] [%^%L%$] [thread %t] %v");

    spdlog::info("Welcome to spdlog!");
    spdlog::error("Some error message with arg: {}", 1);
    spdlog::info("Elapsed time: {}", sw);

    spdlog::warn("Easy padding in numbers like {:08d}", 12);
    spdlog::critical("Support for int: {0:d};  hex: {0:x};  oct: {0:o}; bin: {0:b}", 42);
    spdlog::info("Support for floats {:03.2f}", 1.23456);
    spdlog::info("Positional args are {1} {0}..", "too", "supported");
    spdlog::info("{:<30}", "left aligned");
    spdlog::info("Elapsed time: {}", sw);

}

//' spdlog Logging Lever Setter
//'
//' A helper function to turn a logging level given as string
//' into the current logging level
//'
//' @param name A string with the logging level. Value understood are,
//' in decreasing verbosity \sQuote{trace}, \sQuote{debug}, \sQuote{info},
//' \sQuote{warning}, \sQuote{error}, \sQuote{critical}, and \sQuote{off}.
//' Unrecognised names are equivalent to \sQuote{off}.
//' @return Nothing is returned.
// [[Rcpp::export]]
void setLogLevel(const std::string &name) {
    spdlog::set_level(spdlog::level::from_str(name));
}

```

**Comment by jdstamp** [comment] 2021-04-27 17:01
I do not get the error anymore when using this header file:

```
#pragma once

#include <Rcpp.h>

#ifdef _OPENMP
#include <omp.h>
#endif

#define SPDLOG_DISABLE_DEFAULT_LOGGER 1
#include <RcppSpdlog>
#include <spdlog/stopwatch.h>           // also support stopwatch feature
```

I deleted the following lines:

```
#define ARMA_64BIT_WORD 1
#include <RcppArmadillo.h>
```

**Comment by eddelbuettel** [comment] 2021-04-27 17:18
> copy MAPIT.h file into rcppspdlog/src

No. Then it is no longer my package.  

Please test it _unchanged_.  Moreover, do not blindly use `usethis::whatever` commands. I have no idea what they do.  I have not written any documentation suggesting anyone you use them (but as you are free to do so).

I do not have time to teach you R, not can I read dozen of long issues.  I tried to give you pointers;  you are free to ignore  them..

All I can tell from you submitted here is that _your_ package has an issue.  You initially claimed _my package_ caused that. I still do not see it, and I plan to close this unless you can actually provided a _minimally complete verifiable example_ showing RcppSpdlog causes the warning.

**Comment by jdstamp** [comment] 2021-04-27 17:36
I appreciate the time you are taking here.

I am not sure what you mean by "test it unchanged". I can reproduce the error without adding files but I have to make changes. 
The error occurs when I try to `#include <RcppArmadillo.h>` in **exampleRsink**:
```

// this portmanteau include also defines the r_sink we use below, and which
// diverts all logging to R via the Rcpp::Rcout replacement for std::cout
#include <RcppArmadillo.h>
#include <RcppSpdlog>
#include <spdlog/stopwatch.h>   		// also support stopwatch feature

...

//' @examples
//' exampleRsink()
// [[Rcpp::export]]
void exampleRsink() {
...
```
Changes to **DESCRIPTION**
```
...
LinkingTo: Rcpp, RcppArmadillo
Imports: Rcpp, RcppArmadillo
...
```

Warning from `devtools::check()`:
> checking compiled code ... WARNING
  File ‘RcppSpdlog/libs/RcppSpdlog.so’:
    Found ‘___assert_rtn’, possibly from ‘assert’ (C)
      Object: ‘exampleRsink.o’
    Found ‘___stderrp’, possibly from ‘stderr’ (C)
      Object: ‘exampleRsink.o’
  
 >Compiled code should not call entry points which might terminate R nor
  write to stdout/stderr instead of to the console, nor use Fortran I/O
  nor system RNGs.
  
  >See ‘Writing portable packages’ in the ‘Writing R Extensions’ manual.

>0 errors ✓ | 1 warning x | 0 notes ✓

This is from a fresh clone with only the manual changes above. The error does not occur when I only include `RcppArmadillo`. Is this a problem with `RcppSpdlog` or `RcppArmadillo`?

**Comment by eddelbuettel** [comment] 2021-04-27 17:43
Good. That is more tangible. We have an interaction between RcppArmadillo and RcppSpdlog, and that is not something I have yet used, tested, or encountered.

As a first approximation you could try reordering. Bad things happen with RcppArmadillo before RcppSpdlog, what happens if you invert? (Because RcppArmadillo checks if Rcpp has already been included this may warn.)

As a second measure you could try to rearrange your source code to have _two_ files instead of one.  One doing RcppArmadillo, another offering logging and exposing a _narrower_ (maybe standard C++ only?) interface using RcppSpdlog.  More work, and should not be needed but such is life.  Sorry for the bother.  We give these packages away as gifts, they may not be suitable in any and all combinations.

I can at least document this, starting by retitling the issue.

**Comment by jdstamp** [comment] 2021-04-27 17:55
Those are great packages that do many things very well. I am very grateful for them to be openly available in the first place.

**Reordering exampleRsink.cpp includes**

```
#include <RcppSpdlog>
#include <RcppArmadillo.h>
#include <spdlog/stopwatch.h>   		// also support stopwatch feature
```
Including `RcppSpdlog` before `RcppArmadillo` produces a compilation error:
>   In file included from exampleRsink.cpp:5:
   /usr/local/lib/R/4.0/site-library/RcppArmadillo/include/RcppArmadillo.h:27:6: error: "The file 'Rcpp.h' should not be included. Please correct to include only 'RcppArmadillo.h'."
       #error "The file 'Rcpp.h' should not be included. Please correct to include only 'RcppArmadillo.h'."
        ^
   1 error generated.
   make: *** [exampleRsink.o] Error 1
   ERROR: compilation failed for package ‘RcppSpdlog’

I will try to determine whether I can solve this issue by rearranging my source code and will report back.

Thank you so much!

**Comment by eddelbuettel** [comment] 2021-04-27 18:00
I expected that with the reordering.  We can try to trick it.  The test does 

```c++
#if defined(Rcpp_hpp) && !defined(COMPILING_RCPPARMADILLO)
    #error "The file 'Rcpp.h' should not be included. Please correct to include only 'RcppArmadillo.h'."
#endif
```

so you could try an `#undef Rcpp_hpp` just before the `#include <RcppArmadillo.h>`.  That said, we did this for a reason so other things may yet happen, but we can at least try.

Likewise someone/somewhere/somehow defines something in RcppArmadillo that leads RcppSpdlog to then go down a different code path with the bad `assert()` and `stderr`.   It may be a lot of work, but it _should be_ findable eventually.  

Splitting the source files surely is work too right now, but it may be the best bet.  Truly sorry that appears to be needed but no better answer yet...

**Comment by eddelbuettel** [comment] 2021-04-27 18:55
I can partially reproduce this on Linux too.  But with the header

```c++
// this portmanteau include also defines the r_sink we use below, and which
// diverts all logging to R via the Rcpp::Rcout replacement for std::cout
#include <RcppSpdlog>
#include <spdlog/stopwatch.h>   		// also support stopwatch feature

#undef Rcpp_hpp
#include <RcppArmadillo.h>
```

in `src/exampleRsink.cpp` I can build and include a simple dummy function (not even exported)

```c++
arma::mat twice(arma::mat x) { return x+x; } 
```

without triggering anything from `R CMD check`.  Not idea (as the `#undef ` is somewhat uncool) but it _works_.   Good enough?

**Comment by jdstamp** [comment] 2021-04-27 19:18
The solution with `#undef Rcpp_hpp` solves the problem of producing a warning. However, it also leads to an object initialized as `arma::mat Lambda(n * d, p);` to be returned as a vector of dimensions `(n * d * p) x 1` later on.

**Comment by eddelbuettel** [comment] 2021-04-27 19:22
You need to calmly try to explain how my one one-liner

```c++
arma::mat twice(arma::mat x) { return x+x; } 
```

would do that.  If you have a different problem with RcppArmadillo maybe you can then provide a _minimally complete verifiable example_ (mcve) for it?  You haven't here.

But as you confirmed that the issue at hand went away, I will close this now.  Should I have overlooked an issue in RcppSpdlog please feel free to reopen, ideally with supporting material and a mcve for it.

**Closed by eddelbuettel** 2021-04-27 19:22 UTC

**Comment by jdstamp** [comment] 2021-04-27 19:50
This is not part of any minimal example but an observation in my package and I mentioned it for completeness.

Just to clarify the observation that changing the order of `#include` together with `#undef` has:

Before changing that, the array of Eigenvalues computed in the C++ part that was returned to the R part of the function was: `Eigenvalues: num [1:15, 1:10]`. 

After adopting the hacky solution this is `Eigenvalues: num [1:150]`.  

This is not desired either. Hence, it is not a solution to my problem.

**Comment by eddelbuettel** [comment] 2021-04-27 19:55
It seems like the project you adopted was not using RcppSpdlog befire.

It also seems like you discovered an interaction between RcppSpdlog and RcppArmadillo.  So maybe your best bet it so leave RcppSpdlog aside as it does not currently fit into your existing project.  Why that happens may be something I might have time to look into.  Until then, maybe your best bet is to not include headers from both in the same file.

**Comment by eddelbuettel** [comment] 2021-04-27 20:54
PS  Spdlog is of course of help for debugging.  You could still add it to your code _but keep it turned off_ for example by keeping an 

```c++
#if defined(WithRcppSpdlog)
#include <RcppSpdlog.h>
#endif
```

in the code so that 'normal' builds do not see it.  That way you get to use it locally (to debug) or 'by appointment' (if you tell your users to enable it in a rebuild) but CRAN leaves you alone with the warning.   That's basically where we were before I worked out the expanded use example which, as you noticed, can still be fragile.
